name: CI

on: push

jobs:
  lint:
    uses: jill64/workflows/.github/workflows/lint.yml@main
  build:
    uses: jill64/workflows/.github/workflows/build.yml@main
  coverage:
    uses: jill64/workflows/.github/workflows/coverage.yml@main
